### ISSUE TITLE
Why is this 45.3kB unpacked?!

### ISSUE THREAD

**Issue by digeomel** [KingMario/ngx-trim-directive#1]
On the main NPM registry (https://www.npmjs.com/package/ngx-trim-directive) the module is listed as being 45.3kB unpacked:

![image](https://github.com/KingMario/ngx-trim-directive/assets/3295889/c85a6fd7-da99-47cc-bddc-5e56445b3602)

How is this possible? This is just a simple directive in one file. What am I missing?

**Comment by KingMario** [comment]
It's built by Angular CLI and it contains the packed files:

https://unpkg.com/browse/ngx-trim-directive@3.0.0/
