### ISSUE TITLE
Incorrect "main" property in the package.json

### ISSUE THREAD

**Issue by DmitryEfimenko** [KingMario/ngx-trim-directive#2]
The `main` property in the [package.json](https://github.com/KingMario/ngx-trim-directive/blob/main/projects/ngx-trim-directive/package.json#L19C12-L19C22) is pointing to an non-existing file. I think this property may not even be needed, but not sure about it.
```json
"main": "index.d.js",
```

Due to this issue, I'm unable to use this directive on StackBlitz.

https://stackblitz.com/edit/stackblitz-starters-5zxcgq?file=src%2Fmain.ts

**Comment by KingMario** [comment]
Hi @DmitryEfimenko, looking at <a href="https://www.npmjs.com/package/ngx-trim-directive?activeTab=code" target="_blank">the code tab of the npm package</a>, the file index.d.js does exist.

This could be an issue of stackblitz.

**Comment by DmitryEfimenko** [comment]
The file that exists is `index.d.ts`. The file that it's looking for is `index.d.js`.

Also, it's a bit strange that the main file in the source code is `.d.ts`. This convention is usually reserved for type definitions.

**Comment by KingMario** [comment]
Thanks @DmitryEfimenko 

Fixed in version 3.0.1 by removing the main property.
